version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - WOLFRAM_APP_ID=${WOLFRAM_APP_ID}
      - SERPAPI_KEY=${SERPAPI_KEY}
    env_file:
      - .env
